name: Publish app to github pages
run-name: Build and Deploy page using GitHub Actions 🚀
permissions:
  contents: read
  pages: write
  id-token: write
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node 17
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install node modules
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Upload page artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build
          name: github-pages
          retention-days: 1

  deploy:

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy page
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages


